version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: beatsheets
      POSTGRES_USER: nestjs_user
      POSTGRES_PASSWORD: nestjs_password
    volumes:
      - ./data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: nestjs_user
      DB_PASSWORD: nestjs_password
      DB_NAME: beatsheets
